name: "Test the inspector against a corpus"
on:
  push:
  pull_request:
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "DeterminateSystems/nix-installer-action@main"
      - uses: "DeterminateSystems/magic-nix-cache-action@main"
      - name: Check formatting
        if: success() || failure()
        run: |
          nix run nixpkgs#nixpkgs-fmt -- --check .
      - name: Ensure evaluating DeterminateSystems/flake-checker/=0.1.19 without output paths produces the right result
        if: success() || failure()
        run: |
          nix eval --json \
            --override-input flake https://flakehub.com/f/DeterminateSystems/flake-checker/=0.1.19 \
            --no-write-lock-file '.#contents.excludingOutputPaths' \
            | nix run nixpkgs\#gron > corpus/DeterminateSystems/flake-checker/=0.1.19/excluding.output
          diff corpus/DeterminateSystems/flake-checker/=0.1.19/excluding.expect corpus/DeterminateSystems/flake-checker/=0.1.19/excluding.output

      - name: Ensure evaluating DeterminateSystems/flake-checker/=0.1.19 with output paths produces the right result
        if: success() || failure()
        run: |
          nix eval --json \
              --override-input flake https://flakehub.com/f/DeterminateSystems/flake-checker/=0.1.19 \
              --no-write-lock-file '.#contents.includingOutputPaths' \
              | nix run nixpkgs\#gron > corpus/DeterminateSystems/flake-checker/=0.1.19/including.output
          diff corpus/DeterminateSystems/flake-checker/=0.1.19/including.expect corpus/DeterminateSystems/flake-checker/=0.1.19/including.output
